domain: "https://docs.discordapps.dev"
baseurl: ""
url: "https://docs.discordapps.dev"
encoding: utf-8

include:
  - '_pages'

collections:
  documentation:
    output: true
    permalink: /posts/:path/

defaults:
  -
    scope:
      path: ''
      type: documentation
    values:
      layout: default
